---
- name: Download ruby-install
  get_url:
    url: "https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz"
    dest: /root/ruby-install.tar.gz
    validate_certs: no

- name: Unpack ruby-install
  shell: |
    cd /root
    tar -xzvf /root/ruby-install.tar.gz

- name: Install ruby-install
  make: chdir=/root/ruby-install-{{ ruby_install_version }} target=install

- name: Create rubies directory
  file: path=/opt/rubies/ state=directory mode=0755 owner=root group=root

- name: Check for rubies
  stat: path=/opt/rubies/ruby-{{ ruby_version }}/
  register: rubies_installed

- name: Install the Ruby version {{ ruby_version }}
  command: ruby-install ruby {{ ruby_version }}
  when: rubies_installed.stat.isdir is not defined
